name: ZenToDo
description: ZenToDo — кроссплатформенный ToDo-приложение с японским стилем
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <5.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Ассеты - JPG тоже работает!
  assets:
    - assets/images/
  
  # Иконки приложения (поддерживает JPG)
  icons:
    android: true
    ios: true
    image_path_ios: "assets/images/icon.jpg"
    image_path_android: "assets/images/icon.jpg"
    adaptive_icon_background: "#FF99CC"
    adaptive_icon_foreground: "assets/images/icon.jpg"
